### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by roggif** [AIDA-HQ/AIDApp-core#1]
# High Priority
- [ ] Allow the user to pick a custom upwind position
- [ ] keff -> (Teff)2
- [ ] round numbers to 5 decimal numbers
- [ ] Add **instructions**/whatsThis:
  - [Info software.pdf](https://github.com/AIDA-HQ/AIDApp/files/9188888/Info.software.pdf)
- [ ] Rename the "Values" class to something else
- [ ] Add clear button to restart the procedure without closing the program
- [ ] Calculate average of the last two values of Vp_DB to calculate Vy_DB, now i’m just using the latest
- [ ] **Implement exceptions** to alert the user of errors

# Low(er) priority
- [ ] Localisation support
  - [ ] Add toggle to change language
  - [x] ~~Italian:~~
    - [x] ~~k(F) -> k(S)~~
    - [x] ~~muDB -> muC~~
    - [x] ~~kDB -> kC~~
- [ ] Automatically calculate zonation values
- [ ] Fix check amount (from 0.5 to 5)
- [ ] Adopt snake case for variables
- [ ] Replace Matplotlib with something lighter
- [ ] Add button to ~~show~~/hide the graph
- [ ] Add an **icon**
- [ ] Create a method to handle GUI output values
- [ ] Add toggle(s) to convert pushover values to "custom" unit of measure
- [ ] Let the user **choose** the **"check" value** (currently it's 0.5)
- [ ] Build workflow to package the app for macOS and Linux
- [ ] Write some kind of documentation
- [ ] Make the code run faster
  - [ ] Remove "self" to gui.py variables when it isn't needed
  - [x] ~~**Decrease** the amount of **for loops**~~ e716c85
---
# Done
- [x] Write all the docstrings
- [x] Fix attribute-defined-outside-init
- [x] ~~**Allow to import and export input and output values**~~
- [x] ~~Multiline selection of output data~~
- [x] ~~Automatically calculate the values for the **ADRS spectrum**~~
- [x] ~~Change ADRS iteration~~
- [x] ~~Calculate and display values of upwinds~~
- [x] ~~Let the user **submit pushover curve by** selecting a .txt file containing the values~~ 2ab75c2
- [x] ~~Use actual greek symbols~~ 6ebd1a6
- [x] ~~Make the output values selectable by mouse~~ fb1b892
- [x] ~~Add unit of measure to GUI labels~~ fb8fc10 f539fc4
- [x] ~~Accept storey masses with decimals~~ 6b36f0c
- [x] ~~Add bar to scroll the view~~
